### ISSUE TITLE
Content Negotiation API's example

### ISSUE THREAD

**Issue by marleyiam** [slimphp/Slim-Middleware#8]
Hi! Does anybody could show me an example about how to set and use Content Negotiation? Cheers!

**Comment by silentworks** [comment]
Can you post this in one place and stop spamming please, if you post it on http://help.slimframework.com/ you are more likely to get help there as the issues section is meant for issue with the actual codebase, not a how to use.

**Comment by marleyiam** [comment]
you're welcome.
